spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pk?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root


mybatis:
  mapper-locations: classpath:top/cplpig/mapper/*.xml  #注入Mapper配置文件位置
  type-aliases-package: top.cplpig.entity  #别名，同样为类名或者类名首字母小写  User => User|user
  configuration:
    mapUnderscoreToCamelCase: true  #数据库 字段下划线 转JAVA大写字母
